import os

if __name__ != "__main__":
    print("This script is not meant to be imported.")
    exit(1)

__version__ = (0, 9, 0)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Generate include/pltxt2htm/version.hh
INCLUDE_VERSION_PATH = os.path.join(SCRIPT_DIR, "include", "pltxt2htm", "version.hh")

context = f"""/**
 * @file version.hh
 * @brief Version information for pltxt2htm library
 * @note This file is automatically generated by gen_version.py, do not edit manually
 */

#pragma once

#include <cstddef>

namespace pltxt2htm::version {{

/**
 * @brief Major version number - incremented for breaking changes
 * @note Breaking changes include API changes that are not backward compatible
 */
inline constexpr ::std::size_t major{{{__version__[0]}}};

/**
 * @brief Minor version number - incremented for new features without breaking changes
 * @note New features that are backward compatible increment this number
 */
inline constexpr ::std::size_t minor{{{__version__[1]}}};

/**
 * @brief Patch version number - incremented for bug fixes without new features
 * @note Bug fixes and minor improvements increment this number
 */
inline constexpr ::std::size_t patch{{{__version__[2]}}};

}} // namespace pltxt2htm::version
"""

with open(INCLUDE_VERSION_PATH, "w", newline="") as f:
    f.write(context)

# Generate c/version.lua
C_VERSION_PATH = os.path.join(SCRIPT_DIR, "c", "xmake.lua")

context = f'set_version("{__version__[0]}.{__version__[1]}.{__version__[2]}", {{soname = true}}) -- This line has been generated by gen_version.py, do not edit'

with open(C_VERSION_PATH, "r+", newline="") as f:
    _context = f.read().splitlines()
    _context[0] = context
    f.seek(0)
    f.write("".join(line + "\n" for line in _context))

# Generate py/version.py
PY_VERSION_PATH = os.path.join(SCRIPT_DIR, "py", "version.py")

context = f"""# Generated by gen_version.py, do not edit
__version__ = "{__version__[0]}.{__version__[1]}.{__version__[2]}"
"""

with open(PY_VERSION_PATH, "w", newline="") as f:
    f.write(context)

# Generate rust/pltxt2htm/version.rs
RUST_VERSION_PATH = os.path.join(
    SCRIPT_DIR, "rust", "pltxt2htm", "src", "pltxt2htm", "version.rs"
)

context = f"""// Generated by gen_version.py, do NOT edit
pub const MAJOR: usize = {__version__[0]};
pub const MINOR: usize = {__version__[1]};
pub const PATCH: usize = {__version__[2]};
"""

with open(RUST_VERSION_PATH, "w", newline="") as f:
    f.write(context)
