if __name__ != "__main__":
    raise Exception("This file can't be imported")

import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(SCRIPT_DIR, ".gitignore")) as f:
    context = f.read()

_, _, rest = context.partition('\n')

context = "# Generated by gen_dockerignore.py, do not edit\n" + rest

with open(os.path.join(SCRIPT_DIR, ".dockerignore"), "w", newline='') as f:
    f.write(context)
