set_version("0.5.0", {soname = true}) -- This line has been generated by gen_version.py, do not edit

set_policy("check.auto_ignore_flags", false)

set_allowedmodes("debug", "release")
add_rules("mode.debug", "mode.release")

includes("../xmake/*.lua")
set_languages("c++23")
set_encodings("utf-8")

add_files("pltxt2htm.cc")
add_includedirs("$(projectdir)/../include")

if is_plat("windows") or is_plat("mingw") then
    add_syslinks("ntdll")
end

target("pltxt2htm", function ()
    set_kind("$(kind)")

    on_config(function(target)
        if not target:get("kind") == "static" and not target:get("kind") == "shared" then
            print("error: kind must be static or shared")
            os.exit(1)
        end

        if is_mode("debug") then
            set_symbols("debug")
        end

        local toolchains = target:tool("cxx")
        if path.basename(toolchains) == "clang++" or path.basename(toolchains) == "clang" then
            target:add("shflags", "-fuse-ld=lld")
            if is_mode("release") then
                target:add("ldflags", "-flto")
            end
        end

        if path.basename(toolchains) == "clang++"
                or path.basename(toolchains) == "clang"
                or path.basename(toolchains) == "gcc"
                or path.basename(toolchains) == "g++" then
            target:add("cxxflags", "-fno-exceptions")
            target:add("cxxflags", "-fno-rtti")
            target:add("cxxflags", "-fno-unwind-tables")
            target:add("cxxflags", "-fno-asynchronous-unwind-tables")
            target:add("cxxflags", "-fvisibility=hidden")
            target:add("cxxflags", "-fvisibility-inlines-hidden")
            if is_mode("release") then
                target:add("cxxflags", "-fno-ident")
            end
        end
    end)
end)
