#!/usr/bin/env python3
"""Translate pltxt2htm C++ API into C# (experimental)."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    from clang import cindex
except Exception as exc:  # pragma: no cover
    raise SystemExit(
        "Unable to import clang.cindex. Install libclang Python bindings first."
    ) from exc


TYPE_MAP = {
    "bool": "bool",
    "char": "byte",
    "signed char": "sbyte",
    "unsigned char": "byte",
    "short": "short",
    "unsigned short": "ushort",
    "int": "int",
    "unsigned int": "uint",
    "long": "nint",
    "unsigned long": "nuint",
    "long long": "long",
    "unsigned long long": "ulong",
    "float": "float",
    "double": "double",
    "char8_t const *": "string",
    "char const *": "string",
    "void": "void",
}


@dataclass(slots=True)
class FunctionDecl:
    name: str
    result_type: str
    params: list[tuple[str, str]]
    is_constexpr: bool


def normalize_cpp_type(cpp_type: str) -> str:
    t = " ".join(cpp_type.replace("&", " & ").replace("*", " * ").split())
    t = t.replace("std ::", "std::").replace("fast_io ::", "fast_io::")
    return t.strip()


def cpp_type_to_cs(cpp_type: str) -> str:
    t = normalize_cpp_type(cpp_type)
    t = t.replace("constexpr ", "")

    if t in TYPE_MAP:
        return TYPE_MAP[t]
    if t.endswith("const &"):
        t = t[:-7].strip()
    if t.startswith("fast_io::vector<"):
        inner = t.removeprefix("fast_io::vector<").removesuffix(">")
        return f"List<{cpp_type_to_cs(inner)}>"
    if t.startswith("std::vector<"):
        inner = t.removeprefix("std::vector<").removesuffix(">")
        return f"List<{cpp_type_to_cs(inner)}>"
    if t.startswith("fast_io::basic_string<") or t.startswith("std::basic_string<"):
        return "string"
    if "char8_t" in t and ("*" in t or "string_view" in t):
        return "string"
    if t == "std::size_t":
        return "nuint"
    if t == "std::ptrdiff_t":
        return "nint"

    sanitized = re.sub(r"[^0-9a-zA-Z_:<>]", "", t)
    sanitized = sanitized.replace("::", ".")
    return sanitized or "object"


def preprocess_header(header: Path, include_root: Path, clangpp: str) -> Path:
    fd, path = tempfile.mkstemp(suffix=".ii", prefix="pltxt2htm_")
    os.close(fd)
    out = Path(path)
    cmd = [
        clangpp,
        "-std=c++23",
        "-E",
        "-P",
        str(header),
        "-I",
        str(include_root),
        "-o",
        str(out),
    ]
    subprocess.run(cmd, check=True)
    return out


def iter_function_decls(node: cindex.Cursor) -> Iterable[cindex.Cursor]:
    for child in node.get_children():
        if child.kind in {
            cindex.CursorKind.FUNCTION_DECL,
            cindex.CursorKind.CXX_METHOD,
        }:
            yield child
        yield from iter_function_decls(child)


def collect_functions(source: Path, include_root: Path) -> list[FunctionDecl]:
    index = cindex.Index.create()
    tu = index.parse(
        str(source),
        args=["-std=c++23", f"-I{include_root}"],
        options=cindex.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD,
    )

    funcs: list[FunctionDecl] = []
    seen: set[tuple[str, int]] = set()
    for cursor in iter_function_decls(tu.cursor):
        if cursor.location.file is None:
            continue
        if "pltxt2htm" not in str(cursor.location.file):
            continue
        name = cursor.spelling
        if not name or name.startswith("operator"):
            continue

        key = (name, len(list(cursor.get_arguments())))
        if key in seen:
            continue
        seen.add(key)

        params: list[tuple[str, str]] = []
        for idx, arg in enumerate(cursor.get_arguments()):
            pname = arg.spelling or f"arg{idx}"
            ptype = cpp_type_to_cs(arg.type.spelling)
            params.append((ptype, pname))

        funcs.append(
            FunctionDecl(
                name=name,
                result_type=cpp_type_to_cs(cursor.result_type.spelling),
                params=params,
                is_constexpr="constexpr" in cursor.displayname,
            )
        )

    funcs.sort(key=lambda f: f.name)
    return funcs


def build_cs(funcs: list[FunctionDecl], src: Path) -> str:
    lines: list[str] = []
    lines.append("// <auto-generated />")
    lines.append(f"// Source: {src}")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append("namespace Pltxt2Htm.Translated")
    lines.append("{")
    lines.append("    public static class Pltxt2htmApi")
    lines.append("    {")
    lines.append("        public static void Terminate(string reason)")
    lines.append("            => throw new InvalidOperationException(reason);")
    lines.append("")
    lines.append("        public static void Unreachable(string reason)")
    lines.append("            => throw new UnreachableException(reason);")
    lines.append("")

    for fn in funcs:
        params = ", ".join(f"{t} {n}" for t, n in fn.params)
        lines.append(f"        public static {fn.result_type} {fn.name}({params})")
        lines.append("        {")
        lines.append("            // TODO: port function body from translated C++ AST.")
        if fn.result_type == "void":
            lines.append("            throw new NotImplementedException();")
        else:
            lines.append("            throw new NotImplementedException();")
        lines.append("        }")
        lines.append("")

    lines.append("    }")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Translate include/pltxt2htm C++ headers into C# (experimental)."
    )
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--include", type=Path, default=None)
    parser.add_argument("--clangpp", default=os.environ.get("CLANGPP", "clang++"))
    args = parser.parse_args()

    header = args.header.resolve()
    include_root = (args.include or header.parents[2]).resolve()

    preprocessed = preprocess_header(header, include_root, args.clangpp)
    try:
        funcs = collect_functions(preprocessed, include_root)
        output = build_cs(funcs, header)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output, encoding="utf-8")
    finally:
        preprocessed.unlink(missing_ok=True)

    print(f"Generated {args.output} with {len(funcs)} function stubs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
