/**
 * @file version.hh
 * @brief Version information for pltxt2htm library
 * @note This file is automatically generated by gen_version.py, do not edit manually
 */

#pragma once

#include <cstddef>

namespace pltxt2htm::version {

/**
 * @brief Major version number - incremented for breaking changes
 * @note Breaking changes include API changes that are not backward compatible
 */
inline constexpr ::std::size_t major{0};

/**
 * @brief Minor version number - incremented for new features without breaking changes
 * @note New features that are backward compatible increment this number
 */
inline constexpr ::std::size_t minor{10};

/**
 * @brief Patch version number - incremented for bug fixes without new features
 * @note Bug fixes and minor improvements increment this number
 */
inline constexpr ::std::size_t patch{0};

} // namespace pltxt2htm::version
