// Generated by gen_version.py, do not edit
#pragma once

#include <cstddef>

namespace pltxt2htm::version {

// For breaking change
inline constexpr ::std::size_t major{0};
// For new features without breaking change
inline constexpr ::std::size_t minor{6};
// For bug fixes without new features
inline constexpr ::std::size_t patch{1};

} // namespace pltxt2htm::version
