"""
Generate a Ninja build file for clang-format - fixed version without stamp files.
"""

import os
import sys


def find_cpp_files(root_dirs):
    """Find all C/C++ source files in the given directories."""
    extensions = {".cc", ".cpp", ".h", ".hh", ".hpp", ".cppm", ".c", ".inc"}
    skip_dir_components = {"build", ".pixi"}
    files = []

    for directory in root_dirs:
        if not os.path.isdir(directory):
            print(
                f"Warning: Directory '{directory}' not found, skipping.",
                file=sys.stderr,
            )
            continue

        for root, dirs, filenames in os.walk(directory):
            rel_root = root.replace("\\", "/")

            if "-pltxt2htm-" in rel_root:
                dirs[:] = []
                continue

            # Prune unwanted subtrees to avoid walking them entirely
            dirs[:] = [d for d in dirs if d not in skip_dir_components]

            for filename in filenames:
                if os.path.splitext(filename)[1] in extensions:
                    files.append(f"{rel_root}/{filename}")

    return sorted(files)


def generate_ninja_file(files, output_path: str):
    """Generate a Ninja build file for parallel formatting."""
    command = "clang-format -i $in"

    with open(output_path, "w", newline="\n") as f:
        f.write("# Generated by generate_format_ninja.py\n")
        f.write("rule format\n")
        f.write(f"  command = {command}\n")
        f.write("  description = Formatting $in\n\n")

        targets = []
        for source_file in files:
            # Create a unique target name that doesn't conflict with the source file
            target_name = source_file.replace("/", "_").replace(".", "_") + "_formatted"
            targets.append(target_name)
            f.write(f"build {target_name}: format {source_file}\n")

        f.write(f"\nbuild format: phony {' '.join(targets)}\n")
        f.write(f"\ndefault format\n")


def main():
    SCRIPT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    search_dirs = [
        "tests",
        "examples",
        "include/pltxt2htm",
        "wasm",
        "cmd",
        "py",
        "fuzzing",
        "c",
        "cxxmodule/pltxt2htm",
        "cxxmodule/examples",
        "cxxmodule/tests",
    ]
    print(f"Scanning: {', '.join(search_dirs)}")

    source_files = find_cpp_files(search_dirs)

    if not source_files:
        print("Error: No C/C++ files found.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(source_files)} files")

    output_path = os.path.join(SCRIPT_DIR, "format_cpp.ninja")
    generate_ninja_file(source_files, output_path)
    print(f"Generated format_cpp.ninja")
    print("Run: ninja -f format_cpp.ninja")


if __name__ == "__main__":
    main()
