#!/usr/bin/env python3
"""Generate Windows API declarations and MSVC import-symbol aliases."""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
import shutil
import subprocess
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
SYMBOL_ROOT = ROOT / "include" / "pltxt2htm" / "details" / "symbols"


@dataclasses.dataclass(frozen=True)
class Symbol:
    export_name: str
    return_type: str
    parameters: tuple[str, ...]
    nodiscard: bool = False


@dataclasses.dataclass(frozen=True)
class Library:
    api: str
    name: str
    namespace: str
    macro_prefix: str
    probe_definitions: str
    symbols: tuple[Symbol, ...]


LIBRARIES = (
    Library(
        api="nt",
        name="ntdll",
        namespace="pltxt2htm::details::symbols::nt",
        macro_prefix="PLTXT2HTM_DETAIL_NT",
        probe_definitions="""using Handle = void*;
using NtStatus = long;
struct SrwLock {
    void* pointer;
};""",
        symbols=(
            Symbol(
                "RtlCaptureStackBackTrace",
                "unsigned short",
                ("unsigned long", "unsigned long", "void**", "unsigned long*"),
                nodiscard=True,
            ),
            Symbol(
                "RtlTryAcquireSRWLockExclusive",
                "unsigned char",
                ("SrwLock*",),
                nodiscard=True,
            ),
            Symbol(
                "RtlAcquireSRWLockExclusive",
                "void",
                ("SrwLock*",),
            ),
            Symbol(
                "RtlReleaseSRWLockExclusive",
                "void",
                ("SrwLock*",),
            ),
            Symbol(
                "NtDuplicateObject",
                "NtStatus",
                ("Handle", "Handle", "Handle", "Handle*", "unsigned long", "unsigned long", "unsigned long"),
                nodiscard=True,
            ),
            Symbol(
                "NtClose",
                "NtStatus",
                ("Handle",),
                nodiscard=True,
            ),
        ),
    ),
    Library(
        api="win32",
        name="kernel32",
        namespace="pltxt2htm::details::symbols::win32",
        macro_prefix="PLTXT2HTM_DETAIL_WIN32",
        probe_definitions="""using Handle = void*;
using ModuleHandle = void*;
using Procedure = __INTPTR_TYPE__(__stdcall*)();""",
        symbols=(
            Symbol(
                "LoadLibraryExW",
                "ModuleHandle",
                ("wchar_t const*", "Handle", "unsigned long"),
                nodiscard=True,
            ),
            Symbol(
                "GetProcAddress",
                "Procedure",
                ("ModuleHandle", "char const*"),
                nodiscard=True,
            ),
            Symbol(
                "FreeLibrary",
                "int",
                ("ModuleHandle",),
                nodiscard=True,
            ),
        ),
    ),
    Library(
        api="win32",
        name="dbghelp",
        namespace="pltxt2htm::details::symbols::win32",
        macro_prefix="PLTXT2HTM_DETAIL_WIN32",
        probe_definitions="""using Handle = void*;
struct SymbolInfo;
struct ImageHlpLine64;""",
        symbols=(
            Symbol(
                "SymInitialize",
                "int",
                ("Handle", "char const*", "int"),
                nodiscard=True,
            ),
            Symbol(
                "SymRefreshModuleList",
                "int",
                ("Handle",),
                nodiscard=True,
            ),
            Symbol(
                "SymCleanup",
                "int",
                ("Handle",),
                nodiscard=True,
            ),
            Symbol(
                "SymFromAddr",
                "int",
                ("Handle", "::std::uint64_t", "::std::uint64_t*", "SymbolInfo*"),
                nodiscard=True,
            ),
            Symbol(
                "SymGetLineFromAddr64",
                "int",
                ("Handle", "::std::uint64_t", "unsigned long*", "ImageHlpLine64*"),
                nodiscard=True,
            ),
        ),
    ),
)


MSVC_TARGETS = (
    ("i686", "i686-pc-windows-msvc"),
    ("x64", "x86_64-pc-windows-msvc"),
    ("arm32", "armv7-pc-windows-msvc"),
    ("arm64", "aarch64-pc-windows-msvc"),
    ("arm64ec", "arm64ec-pc-windows-msvc"),
)


GENERATED_NOTICE = "// Generated by scripts/gen_windows_symbols.py. Do not edit.\n"

PROBE_TYPES = {
    "Handle": "void*",
    "Handle*": "void**",
    "ModuleHandle": "void*",
    "NtStatus": "long",
    "Procedure": "void*",
    "SrwLock*": "void*",
    "SymbolInfo*": "void*",
    "ImageHlpLine64*": "void*",
    "::std::uint64_t": "__UINT64_TYPE__",
    "::std::uint64_t*": "__UINT64_TYPE__*",
}

LOCAL_PROBE_TYPES = {
    "::std::uint64_t": "__UINT64_TYPE__",
    "::std::uint64_t*": "__UINT64_TYPE__*",
}


def format_parameters(parameters: tuple[str, ...]) -> str:
    return ", ".join(parameters)


def probe_type(type_name: str) -> str:
    return PROBE_TYPES.get(type_name, type_name)


def local_probe_type(type_name: str) -> str:
    return LOCAL_PROBE_TYPES.get(type_name, type_name)


def declaration(symbol: Symbol, library: Library, x86_stack_bytes: int) -> str:
    prefix = library.macro_prefix
    attribute = "[[nodiscard]]\n" if symbol.nodiscard else ""
    suffix = f" {prefix}_ASM_NAME({symbol.export_name}, {x86_stack_bytes})"
    return (
        f"{attribute}{prefix}_DLLIMPORT {symbol.return_type} {prefix}_CALL {symbol.export_name}"
        f"({format_parameters(symbol.parameters)}) noexcept{suffix};\n"
    )


def generate_declarations(library: Library, x86_stack_bytes: dict[str, int]) -> str:
    result = [GENERATED_NOTICE, "\n"]
    result.extend(
        declaration(symbol, library, x86_stack_bytes[symbol.export_name])
        for symbol in library.symbols
    )
    return "".join(result)


def local_probe_source(symbol: Symbol, library: Library) -> str:
    result = local_probe_type(symbol.return_type)
    parameters = format_parameters(tuple(local_probe_type(parameter) for parameter in symbol.parameters))
    return f"""namespace {library.namespace} {{
{library.probe_definitions}

__declspec(dllimport) {result} __stdcall {symbol.export_name}({parameters}) noexcept;
}}

auto* volatile pltxt2htm_probe = &::{library.namespace}::{symbol.export_name};
"""


def export_probe_source(symbol: Symbol) -> str:
    result = probe_type(symbol.return_type)
    parameters = format_parameters(tuple(probe_type(parameter) for parameter in symbol.parameters))
    return f"""extern \"C\" __declspec(dllimport) {result} __stdcall {symbol.export_name}({parameters}) noexcept;

auto* volatile pltxt2htm_probe = &{symbol.export_name};
"""


def undefined_imports(
    source_text: str,
    symbol: Symbol,
    target: str,
    clang: str,
    llvm_nm: str,
    temporary_directory: pathlib.Path,
    stem: str,
) -> tuple[str, ...]:
    source = temporary_directory / f"{stem}.cc"
    object_file = temporary_directory / f"{stem}.obj"
    source.write_text(source_text, encoding="ascii", newline="\n")
    compile_result = subprocess.run(
        [clang, f"--target={target}", "-std=c++23", "-c", str(source), "-o", str(object_file)],
        check=False,
        capture_output=True,
        text=True,
    )
    if compile_result.returncode != 0:
        raise RuntimeError(
            f"clang failed for {symbol.export_name} ({target}):\n{compile_result.stderr.strip()}"
        )
    nm_result = subprocess.run(
        [llvm_nm, "--undefined-only", "--format=posix", str(object_file)],
        check=False,
        capture_output=True,
        text=True,
    )
    if nm_result.returncode != 0:
        raise RuntimeError(
            f"llvm-nm failed for {symbol.export_name} ({target}):\n{nm_result.stderr.strip()}"
        )
    names = [line.split()[0] for line in nm_result.stdout.splitlines() if line.strip()]
    imported = tuple(name for name in names if "__imp_" in name)
    if not imported:
        raise RuntimeError(
            f"could not identify import symbol for {symbol.export_name} ({target}); found: {names}"
        )
    return imported


def import_flavor(name: str) -> str:
    return "aux" if "__imp_aux_" in name else "native"


def undefined_symbols(
    symbol: Symbol,
    library: Library,
    target: str,
    clang: str,
    llvm_nm: str,
    temporary_directory: pathlib.Path,
) -> tuple[tuple[str, str], ...]:
    local = undefined_imports(
        local_probe_source(symbol, library), symbol, target, clang, llvm_nm, temporary_directory, "local"
    )
    exported = undefined_imports(
        export_probe_source(symbol), symbol, target, clang, llvm_nm, temporary_directory, "export"
    )
    exported_by_flavor = {import_flavor(name): name for name in exported}
    pairs = tuple((name, exported_by_flavor[import_flavor(name)]) for name in local)
    if len(pairs) != len(exported) or len(exported_by_flavor) != len(exported):
        raise RuntimeError(
            f"could not pair import symbols for {symbol.export_name} ({target}); "
            f"local: {local}; exported: {exported}"
        )
    return pairs


def generate_linker_aliases(
    library: Library, target: str, clang: str, llvm_nm: str
) -> tuple[str, dict[str, int]]:
    result = [GENERATED_NOTICE, "\n"]
    x86_stack_bytes: dict[str, int] = {}
    with tempfile.TemporaryDirectory(prefix="pltxt2htm-symbols-") as temporary:
        temporary_directory = pathlib.Path(temporary)
        for symbol in library.symbols:
            pairs = undefined_symbols(symbol, library, target, clang, llvm_nm, temporary_directory)
            for local, exported in pairs:
                result.append(f'#pragma comment(linker, "/alternatename:{local}={exported}")\n')
            if target.startswith("i686-"):
                match = re.search(r"@(\d+)$", pairs[0][1])
                if match is None:
                    raise RuntimeError(f"missing i686 stdcall decoration for {symbol.export_name}: {pairs[0][1]}")
                x86_stack_bytes[symbol.export_name] = int(match.group(1))
    return "".join(result), x86_stack_bytes


def generated_files(clang: str, llvm_nm: str) -> dict[pathlib.Path, str]:
    result: dict[pathlib.Path, str] = {}
    for library in LIBRARIES:
        directory = SYMBOL_ROOT / library.api
        i686_stack_bytes: dict[str, int] = {}
        for architecture, target in MSVC_TARGETS:
            aliases, target_stack_bytes = generate_linker_aliases(
                library, target, clang, llvm_nm
            )
            result[directory / f"{library.name}_msvc_linker_{architecture}.inc"] = aliases
            i686_stack_bytes.update(target_stack_bytes)
        result[directory / f"{library.name}.inc"] = generate_declarations(library, i686_stack_bytes)
    return result


def resolve_tool(value: str, description: str) -> str:
    resolved = shutil.which(value)
    if resolved is None:
        raise RuntimeError(f"{description} was not found: {value}")
    return resolved


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--clang", default="clang++", help="Clang C++ driver")
    parser.add_argument("--llvm-nm", default="llvm-nm", help="LLVM symbol table dumper")
    arguments = parser.parse_args()

    clang = resolve_tool(arguments.clang, "Clang C++ driver")
    llvm_nm = resolve_tool(arguments.llvm_nm, "llvm-nm")
    files = generated_files(clang, llvm_nm)
    stale: list[pathlib.Path] = []
    for path, content in files.items():
        if arguments.check:
            if not path.exists() or path.read_text(encoding="ascii") != content:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="ascii", newline="\n")

    if stale:
        print("Generated Windows symbol files are stale:")
        for path in stale:
            print(f"  {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
