"""Generate the HTML named character-reference table data."""

from __future__ import annotations

import hashlib
import html.entities
import json
from pathlib import Path


EXPECTED_COUNT = 2125
EXPECTED_SHA256 = "083dc02ec806d6d630ad69cdcd3ebf4b3f04509f8ad00ad8772f8905d285beb4"
OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "include"
    / "pltxt2htm"
    / "details"
    / "parser"
    / "html_named_character_references.inc"
)


def main() -> None:
    """Write the pinned, semicolon-terminated HTML5 entity table."""
    items = sorted(
        (name[:-1], value)
        for name, value in html.entities.html5.items()
        if name.endswith(";")
    )
    canonical = json.dumps(items, ensure_ascii=False, separators=(",", ":")).encode()
    digest = hashlib.sha256(canonical).hexdigest()
    if len(items) != EXPECTED_COUNT or digest != EXPECTED_SHA256:
        raise RuntimeError(
            "html.entities.html5 does not match the pinned HTML5 entity data: "
            f"count={len(items)}, sha256={digest}"
        )
    if sum(len(name) for name, _ in items) > 0xFFFF:
        raise RuntimeError("entity-name blob does not fit in uint_least16_t offsets")
    if any(len(name) > 0xFF or len(value) not in (1, 2) for name, value in items):
        raise RuntimeError("entity data does not fit the generated table representation")

    lines = [
        "/**",
        " * @file html_named_character_references.inc",
        " * @brief Generated data for semicolon-terminated HTML5 named character references.",
        " * @warning Generated by scripts/gen_html_named_character_references.py; do not edit.",
        " */",
        "",
        "// clang-format off",
        "static constexpr char8_t names[] =",
    ]
    for name, _ in items:
        lines.append(f'    u8"{name}"')
    lines[-1] += ";"
    lines.extend(
        [
            "",
            f"static constexpr auto compressed_entries = ::pltxt2htm::container::Array<CompressedEntry, {len(items)}>"
            "{{",
        ]
    )

    offset = 0
    for name, value in items:
        first = ord(value[0])
        second = ord(value[1]) if len(value) == 2 else 0
        lines.append(
            "    {"
            f".name_offset = {offset}, .name_size = {len(name)}, "
            ".reference = {"
            f".first_code_point = char32_t{{0x{first:X}}}, "
            f".second_code_point = char32_t{{0x{second:X}}}"
            "}"
            "},"
        )
        offset += len(name)
    lines.extend(["}};", "// clang-format on", ""])

    OUTPUT.write_bytes("\n".join(lines).encode("utf-8"))


if __name__ == "__main__":
    main()
