import os
import re

if __name__ != "__main__":
    print("This script is not meant to be imported.")
    exit(1)

SCRIPT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSION_FILE = os.path.join(SCRIPT_DIR, "VERSION")

with open(VERSION_FILE) as f:
    version_raw = f.read().strip()

m = re.match(r"^(\d+)\.(\d+)\.(\d+)$", version_raw)
if not m:
    raise RuntimeError(f"VERSION file does not contain a valid semver (expected X.Y.Z), got: {version_raw!r}")

major, minor, patch = int(m.group(1)), int(m.group(2)), int(m.group(3))
version_str = f"{major}.{minor}.{patch}"


def _write_if_changed(path: str, content: str) -> None:
    """Write file only if content has changed, to avoid unnecessary rebuilds."""
    if os.path.exists(path):
        with open(path, newline="") as f:
            if f.read() == content:
                return
    with open(path, "w", newline="") as f:
        f.write(content)


# --- Generate include/pltxt2htm/version.hh ---
INCLUDE_VERSION_PATH = os.path.join(SCRIPT_DIR, "include", "pltxt2htm", "version.hh")

_write_if_changed(INCLUDE_VERSION_PATH, f"""\
/**
 * @file version.hh
 * @brief Version information for pltxt2htm library
 * @note This file is automatically generated by gen_version.py, do not edit manually
 */

#pragma once

#include <cstddef>

namespace pltxt2htm::version {{

/**
 * @brief Major version number - incremented for breaking changes
 * @note Breaking changes include API changes that are not backward compatible
 */
inline constexpr ::std::size_t major{{{major}}};

/**
 * @brief Minor version number - incremented for new features without breaking changes
 * @note New features that are backward compatible increment this number
 */
inline constexpr ::std::size_t minor{{{minor}}};

/**
 * @brief Patch version number - incremented for bug fixes without new features
 * @note Bug fixes and minor improvements increment this number
 */
inline constexpr ::std::size_t patch{{{patch}}};

}} // namespace pltxt2htm::version
""")


# --- Generate py/version.py ---
PY_VERSION_PATH = os.path.join(SCRIPT_DIR, "py", "version.py")

_write_if_changed(PY_VERSION_PATH, f"""\
# Generated by gen_version.py, do not edit
__version__ = "{version_str}"
""")


# --- Update py/pixi.toml ---
PIXI_TOML_PATH = os.path.join(SCRIPT_DIR, "py", "pixi.toml")

with open(PIXI_TOML_PATH, "r+", newline="") as f:
    orig = f.read()
    lines = orig.splitlines()
    in_workspace = False
    found = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == "[workspace]":
            in_workspace = True
        elif in_workspace and stripped.startswith("["):
            in_workspace = False
        if in_workspace and stripped.startswith("version"):
            lines[i] = f'version = "{version_str}"  # Generated by gen_version.py, do not edit'
            found = True
            break
    if not found:
        raise RuntimeError("version not found in [workspace] of pixi.toml")
    new = "".join(line + "\n" for line in lines)
    if new != orig:
        f.seek(0)
        f.truncate()
        f.write(new)


# --- Generate rust/pltxt2htm/version.rs ---
RUST_VERSION_PATH = os.path.join(
    SCRIPT_DIR, "rust", "pltxt2htm", "src", "pltxt2htm", "version.rs"
)

_write_if_changed(RUST_VERSION_PATH, f"""\
// Generated by gen_version.py, do NOT edit
pub const MAJOR: usize = {major};
pub const MINOR: usize = {minor};
pub const PATCH: usize = {patch};
""")


# --- Update rust/*/Cargo.toml ---
for cargo_file in ["libpltxt2htm-sys/Cargo.toml", "pltxt2htm/Cargo.toml"]:
    CARGO_PATH = os.path.join(SCRIPT_DIR, "rust", cargo_file)

    with open(CARGO_PATH, "r+", newline="") as f:
        orig = f.read()
        lines = orig.splitlines()
        in_package = False
        found = False
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped == "[package]":
                in_package = True
            elif in_package and stripped.startswith("["):
                in_package = False
            if in_package and stripped.startswith("version"):
                lines[i] = f'version = "{version_str}"'
                found = True
                break
        if not found:
            raise RuntimeError(f"version not found in [package] of {cargo_file}")
        new = "".join(line + "\n" for line in lines)
        if new != orig:
            f.seek(0)
            f.truncate()
            f.write(new)


# --- Update CMakeLists.txt files ---
CMAKE_FILES = [
    "c/CMakeLists.txt",
    "cmd/CMakeLists.txt",
    "py/CMakeLists.txt",
    "tests/CMakeLists.txt",
    "examples/CMakeLists.txt",
    "fuzzing/CMakeLists.txt",
    "wasm/CMakeLists.txt",
    "cxxmodule/examples/CMakeLists.txt",
]

for cmake_file in CMAKE_FILES:
    CMAKE_PATH = os.path.join(SCRIPT_DIR, cmake_file)

    with open(CMAKE_PATH, "r+", newline="") as f:
        orig = f.read()
        lines = orig.splitlines()
        found = False
        for i, line in enumerate(lines):
            if line.lstrip().startswith("project("):
                # Remove any existing VERSION argument (idempotent)
                line = re.sub(r'\s+VERSION\s+\d+\.\d+\.\d+', '', line)
                # Insert VERSION before the closing paren
                line = line.rstrip()
                if line.endswith(")"):
                    line = line[:-1] + f" VERSION {version_str})"
                else:
                    raise RuntimeError(f"unexpected project() format in {cmake_file}")
                lines[i] = line
                found = True
                break
        if not found:
            raise RuntimeError(f"project(...) not found in {cmake_file}")
        new = "\n".join(lines) + "\n"
        if new != orig:
            f.seek(0)
            f.truncate()
            f.write(new)
