"""
Generate a Ninja build file for clang-tidy.
"""

import os
import sys


def find_cpp_files(root_dirs):
    """Find all C/C++ source files in the given directories."""
    extensions = {".cc", ".cpp", ".h", ".hh", ".hpp", ".cppm", ".c", ".inc"}
    skip_dir_components = {"build", ".pixi"}
    files = []

    for directory in root_dirs:
        if not os.path.isdir(directory):
            print(
                f"Warning: Directory '{directory}' not found, skipping.",
                file=sys.stderr,
            )
            continue

        for root, dirs, filenames in os.walk(directory):
            rel_root = root.replace("\\", "/")

            if "-pltxt2htm-" in rel_root:
                dirs[:] = []
                continue

            dirs[:] = [d for d in dirs if d not in skip_dir_components]

            for filename in filenames:
                if os.path.splitext(filename)[1] in extensions:
                    files.append(f"{rel_root}/{filename}")

    return sorted(files)


def generate_ninja_file(files, output_path: str):
    """Generate a Ninja build file for clang-tidy."""
    cpp_rule = "clang-tidy $in -- -std=c++23 -Iinclude"
    c_rule = "clang-tidy $in -- -std=c99 -Iinclude"

    with open(output_path, "w", newline="\n") as f:
        f.write("# Generated by gen_tidy_ninja.py\n")
        f.write("rule tidy_cpp\n")
        f.write(f"  command = {cpp_rule}\n")
        f.write("  description = Tidying C++ $in\n\n")
        f.write("rule tidy_c\n")
        f.write(f"  command = {c_rule}\n")
        f.write("  description = Tidying C $in\n\n")

        targets = []
        for source_file in files:
            target_name = source_file.replace("/", "_").replace(".", "_") + "_tidy"
            ext = os.path.splitext(source_file)[1]
            is_c = ext == ".c" or (ext == ".h" and source_file.startswith("c/"))
            rule = "tidy_c" if is_c else "tidy_cpp"
            targets.append(target_name)
            f.write(f"build {target_name}: {rule} {source_file}\n")

        f.write(f"\nbuild tidy: phony {' '.join(targets)}\n")
        f.write(f"\ndefault tidy\n")


def main():
    SCRIPT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    search_dirs = [
        "tests",
        "examples",
        "include/pltxt2htm",
        "wasm",
        "cmd",
        "py",
        "fuzzing",
        "c",
    ]
    print(f"Scanning: {', '.join(search_dirs)}")

    source_files = find_cpp_files(search_dirs)

    if not source_files:
        print("Error: No C/C++ files found.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(source_files)} files")

    output_path = os.path.join(SCRIPT_DIR, "tidy_cpp.ninja")
    generate_ninja_file(source_files, output_path)
    print(f"Generated tidy_cpp.ninja")
    print("Run: ninja -f tidy_cpp.ninja")


if __name__ == "__main__":
    main()
