#!/usr/bin/env python3
"""Generate Windows API declarations and MSVC import-symbol aliases."""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
import shutil
import subprocess
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
SYMBOL_ROOT = ROOT / "include" / "pltxt2htm" / "details" / "symbols"


@dataclasses.dataclass(frozen=True)
class Symbol:
    export_name: str
    local_name: str
    return_type: str
    parameters: tuple[str, ...]
    nodiscard: bool = False


@dataclasses.dataclass(frozen=True)
class Library:
    api: str
    name: str
    namespace: str
    macro_prefix: str
    symbols: tuple[Symbol, ...]


LIBRARIES = (
    Library(
        api="nt",
        name="ntdll",
        namespace="pltxt2htm::details::symbols::nt",
        macro_prefix="PLTXT2HTM_DETAIL_NT",
        symbols=(
            Symbol(
                "RtlCaptureStackBackTrace",
                "pltxt2htm_nt_capture_stack_back_trace",
                "unsigned short",
                ("unsigned long", "unsigned long", "void**", "unsigned long*"),
                nodiscard=True,
            ),
            Symbol(
                "RtlTryAcquireSRWLockExclusive",
                "pltxt2htm_nt_try_acquire_srw_lock_exclusive",
                "unsigned char",
                ("SrwLock*",),
                nodiscard=True,
            ),
            Symbol(
                "RtlAcquireSRWLockExclusive",
                "pltxt2htm_nt_acquire_srw_lock_exclusive",
                "void",
                ("SrwLock*",),
            ),
            Symbol(
                "RtlReleaseSRWLockExclusive",
                "pltxt2htm_nt_release_srw_lock_exclusive",
                "void",
                ("SrwLock*",),
            ),
            Symbol(
                "NtDuplicateObject",
                "pltxt2htm_nt_duplicate_object",
                "NtStatus",
                ("Handle", "Handle", "Handle", "Handle*", "unsigned long", "unsigned long", "unsigned long"),
                nodiscard=True,
            ),
            Symbol(
                "NtClose",
                "pltxt2htm_nt_close",
                "NtStatus",
                ("Handle",),
                nodiscard=True,
            ),
        ),
    ),
    Library(
        api="win32",
        name="kernel32",
        namespace="pltxt2htm::details::symbols::win32",
        macro_prefix="PLTXT2HTM_DETAIL_WIN32",
        symbols=(
            Symbol(
                "LoadLibraryExW",
                "pltxt2htm_win32_load_library_ex_w",
                "ModuleHandle",
                ("wchar_t const*", "Handle", "unsigned long"),
                nodiscard=True,
            ),
            Symbol(
                "GetProcAddress",
                "pltxt2htm_win32_get_proc_address",
                "Procedure",
                ("ModuleHandle", "char const*"),
                nodiscard=True,
            ),
            Symbol(
                "FreeLibrary",
                "pltxt2htm_win32_free_library",
                "int",
                ("ModuleHandle",),
                nodiscard=True,
            ),
        ),
    ),
)


MSVC_TARGETS = (
    ("i686", "i686-pc-windows-msvc"),
    ("x64", "x86_64-pc-windows-msvc"),
    ("arm32", "armv7-pc-windows-msvc"),
    ("arm64", "aarch64-pc-windows-msvc"),
    ("arm64ec", "arm64ec-pc-windows-msvc"),
)


GENERATED_NOTICE = "// Generated by scripts/gen_windows_symbols.py. Do not edit.\n"

PROBE_TYPES = {
    "Handle": "void*",
    "Handle*": "void**",
    "ModuleHandle": "void*",
    "NtStatus": "long",
    "Procedure": "void*",
    "SrwLock*": "void*",
}


def format_parameters(parameters: tuple[str, ...]) -> str:
    return ", ".join(parameters)


def probe_type(type_name: str) -> str:
    return PROBE_TYPES.get(type_name, type_name)


def declaration(symbol: Symbol, library: Library, x86_stack_bytes: int) -> str:
    prefix = library.macro_prefix
    attribute = "[[nodiscard]]\n" if symbol.nodiscard else ""
    suffix = f" {prefix}_ASM_NAME({symbol.export_name}, {x86_stack_bytes})"
    return (
        f"{attribute}{prefix}_DLLIMPORT {symbol.return_type} {prefix}_CALL {symbol.local_name}"
        f"({format_parameters(symbol.parameters)}) noexcept{suffix};\n"
    )


def generate_declarations(library: Library, x86_stack_bytes: dict[str, int]) -> str:
    result = [GENERATED_NOTICE, "\n"]
    result.extend(
        declaration(symbol, library, x86_stack_bytes[symbol.export_name])
        for symbol in library.symbols
    )
    return "".join(result)


def probe_source(symbol: Symbol) -> str:
    result = probe_type(symbol.return_type)
    parameters = format_parameters(tuple(probe_type(parameter) for parameter in symbol.parameters))
    return f"""extern \"C\" __declspec(dllimport) {result} __stdcall {symbol.local_name}({parameters}) noexcept;
extern \"C\" __declspec(dllimport) {result} __stdcall {symbol.export_name}({parameters}) noexcept;

auto* volatile pltxt2htm_probe_local = &{symbol.local_name};
auto* volatile pltxt2htm_probe_export = &{symbol.export_name};
"""


def undefined_symbols(
    symbol: Symbol,
    target: str,
    clang: str,
    llvm_nm: str,
    temporary_directory: pathlib.Path,
) -> tuple[tuple[str, str], ...]:
    source = temporary_directory / "probe.cc"
    object_file = temporary_directory / "probe.obj"
    source.write_text(probe_source(symbol), encoding="ascii", newline="\n")
    compile_result = subprocess.run(
        [clang, f"--target={target}", "-std=c++23", "-c", str(source), "-o", str(object_file)],
        check=False,
        capture_output=True,
        text=True,
    )
    if compile_result.returncode != 0:
        raise RuntimeError(
            f"clang failed for {symbol.export_name} ({target}):\n{compile_result.stderr.strip()}"
        )
    nm_result = subprocess.run(
        [llvm_nm, "--undefined-only", "--format=posix", str(object_file)],
        check=False,
        capture_output=True,
        text=True,
    )
    if nm_result.returncode != 0:
        raise RuntimeError(
            f"llvm-nm failed for {symbol.export_name} ({target}):\n{nm_result.stderr.strip()}"
        )
    names = [line.split()[0] for line in nm_result.stdout.splitlines() if line.strip()]
    imported = [name for name in names if "__imp_" in name]
    local = [name for name in imported if symbol.local_name in name]
    exported = {name for name in imported if symbol.export_name in name and symbol.local_name not in name}
    pairs = []
    for local_name in local:
        export_name = local_name.replace(symbol.local_name, symbol.export_name)
        if export_name in exported:
            pairs.append((local_name, export_name))
    if not pairs or len(pairs) != len(local) or len(pairs) != len(exported):
        raise RuntimeError(
            f"could not identify import symbols for {symbol.export_name} ({target}); found: {names}"
        )
    return tuple(pairs)


def generate_linker_aliases(
    library: Library, target: str, clang: str, llvm_nm: str
) -> tuple[str, dict[str, int]]:
    result = [GENERATED_NOTICE, "\n"]
    x86_stack_bytes: dict[str, int] = {}
    with tempfile.TemporaryDirectory(prefix="pltxt2htm-symbols-") as temporary:
        temporary_directory = pathlib.Path(temporary)
        for symbol in library.symbols:
            pairs = undefined_symbols(symbol, target, clang, llvm_nm, temporary_directory)
            for local, exported in pairs:
                result.append(f'#pragma comment(linker, "/alternatename:{local}={exported}")\n')
            if target.startswith("i686-"):
                match = re.search(r"@(\d+)$", pairs[0][1])
                if match is None:
                    raise RuntimeError(f"missing i686 stdcall decoration for {symbol.export_name}: {pairs[0][1]}")
                x86_stack_bytes[symbol.export_name] = int(match.group(1))
    return "".join(result), x86_stack_bytes


def generated_files(clang: str, llvm_nm: str) -> dict[pathlib.Path, str]:
    result: dict[pathlib.Path, str] = {}
    for library in LIBRARIES:
        directory = SYMBOL_ROOT / library.api
        i686_stack_bytes: dict[str, int] = {}
        for architecture, target in MSVC_TARGETS:
            aliases, target_stack_bytes = generate_linker_aliases(
                library, target, clang, llvm_nm
            )
            result[directory / f"{library.name}_msvc_linker_{architecture}.inc"] = aliases
            i686_stack_bytes.update(target_stack_bytes)
        result[directory / f"{library.name}.inc"] = generate_declarations(library, i686_stack_bytes)
    return result


def resolve_tool(value: str, description: str) -> str:
    resolved = shutil.which(value)
    if resolved is None:
        raise RuntimeError(f"{description} was not found: {value}")
    return resolved


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--clang", default="clang++", help="Clang C++ driver")
    parser.add_argument("--llvm-nm", default="llvm-nm", help="LLVM symbol table dumper")
    arguments = parser.parse_args()

    clang = resolve_tool(arguments.clang, "Clang C++ driver")
    llvm_nm = resolve_tool(arguments.llvm_nm, "llvm-nm")
    files = generated_files(clang, llvm_nm)
    stale: list[pathlib.Path] = []
    for path, content in files.items():
        if arguments.check:
            if not path.exists() or path.read_text(encoding="ascii") != content:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="ascii", newline="\n")

    if stale:
        print("Generated Windows symbol files are stale:")
        for path in stale:
            print(f"  {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
